### ISSUE TITLE
Make a more complete demo

### ISSUE THREAD

**Issue by NewAlexandria** [hyperoslo/activeadmin_polymorphic#14]
We tried implementing the demo you show, and even with a fair bit of variation and playing with it, we don't see it working.   Could you update the docs with a more robust example?

Thank you

**Comment by toothfairy** [comment]
@NewAlexandria thanks for report. can you please add your admin model so we can take a closer look?

**Comment by NewAlexandria** [comment]
I lost track of this.  I'll get you an example, in case you would still help.

**Comment by toothfairy** [comment]
@NewAlexandria sure, I'll reopen the issue
