### ISSUE TITLE
Gem assumes you're using default "admin" namespace

### ISSUE THREAD

**Issue by luisbraga** [hyperoslo/activeadmin_polymorphic#15]
It won't work if you set config.default_namespace = false

Sorry, didn't notice in readme

> In plan
> check who it works with: models under a certain namespace

**Comment by toothfairy** [comment]
Sorry for a late answer.
You can user builder option `path_prefix` to redefine namespace for `polymorphic_has_many`. Isolated engine mechanism doesn't allow to fetch that value from activeadmin.
So your code will look some like:
`config.default_namespace = :foobar` in activeadmin initializer
`f.polymorphic_has_many :sections, ..., path_prefix: "foobar"` in admin model definition
